In [1]:
# import library
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM

# seed
import os
seed = 123
os.environ['PYTHONHASHSEED'] = str(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

In [2]:
# dataset
data = np.array([1,2,3,4,5,6,7,8,9,10])

# data preprocess
def split_data(dataset, start_index, end_index, history_size, target_size):
    data = []
    labels = []
    
    start_index = start_index + history_size
    if end_index is None:
        end_index = len(dataset) - target_size
        
    for i in range(start_index, end_index):
        indices = range(i - history_size, i)
        data.append(np.reshape(dataset[indices], (history_size, 1)))
        labels.append(dataset[i+target_size])
    return np.array(data), np.array(labels)

x_train, y_train = split_data(data, 0, 8, 4, 0)
x_val, y_val = split_data(data, 4, 9, 4, 0)
x_test, y_test = split_data(data, 5, None, 4, 0)

print(x_train)
print(y_train)
print(x_val)
print(y_val)
print(x_test)
print(y_test)

[[[1]
  [2]
  [3]
  [4]]

 [[2]
  [3]
  [4]
  [5]]

 [[3]
  [4]
  [5]
  [6]]

 [[4]
  [5]
  [6]
  [7]]]
[5 6 7 8]
[[[5]
  [6]
  [7]
  [8]]]
[9]
[[[6]
  [7]
  [8]
  [9]]]
[10]


In [3]:
# model structure
model = Sequential()
model.add(LSTM(100, input_shape=(4, 1)))
model.add(Dense(10))
model.add(Dense(1))

model.summary()

# model training
model.compile(loss='mse', optimizer='adam')
history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=1000, batch_size=1, verbose=1)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 100)               40800     
_________________________________________________________________
dense (Dense)                (None, 10)                1010      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 41,821
Trainable params: 41,821
Non-trainable params: 0
_________________________________________________________________
Train on 4 samples, validate on 1 samples
Epoch 1/1000
4/4 [==============================] - 3s 630ms/sample - loss: 44.4571 - val_loss: 75.0785
Epoch 2/1000
4/4 [==============================] - 0s 7ms/sample - loss: 37.0254 - val_loss: 61.6870
Epoch 3/1000
4/4 [==============================] - 0s 6ms/sample - loss: 31.0118 - val_loss: 48.5311
Epoch 4/1000
4/4 [==============

4/4 [==============================] - 0s 6ms/sample - loss: 0.0262 - val_loss: 0.4952
Epoch 155/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0299 - val_loss: 0.4941
Epoch 156/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0369 - val_loss: 0.3418
Epoch 157/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0296 - val_loss: 0.3984
Epoch 158/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0344 - val_loss: 0.5039
Epoch 159/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0282 - val_loss: 0.4602
Epoch 160/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0262 - val_loss: 0.3487
Epoch 161/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0286 - val_loss: 0.3813
Epoch 162/1000
4/4 [==============================] - 0s 7ms/sample - loss: 0.0260 - val_loss: 0.3642
Epoch 163/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0269 - val_loss: 0.

4/4 [==============================] - 0s 6ms/sample - loss: 0.0144 - val_loss: 0.1686
Epoch 315/1000
4/4 [==============================] - 0s 7ms/sample - loss: 0.0121 - val_loss: 0.2253
Epoch 316/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0130 - val_loss: 0.1667
Epoch 317/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0109 - val_loss: 0.1778
Epoch 318/1000
4/4 [==============================] - 0s 7ms/sample - loss: 0.0118 - val_loss: 0.1885
Epoch 319/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0133 - val_loss: 0.1632
Epoch 320/1000
4/4 [==============================] - 0s 7ms/sample - loss: 0.0090 - val_loss: 0.2139
Epoch 321/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0145 - val_loss: 0.2104
Epoch 322/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0103 - val_loss: 0.1656
Epoch 323/1000
4/4 [==============================] - 0s 8ms/sample - loss: 0.0225 - val_loss: 0.

4/4 [==============================] - 0s 6ms/sample - loss: 0.0043 - val_loss: 0.0715
Epoch 475/1000
4/4 [==============================] - 0s 7ms/sample - loss: 0.0026 - val_loss: 0.0418
Epoch 476/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0044 - val_loss: 0.0531
Epoch 477/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0045 - val_loss: 0.0736
Epoch 478/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0033 - val_loss: 0.0443
Epoch 479/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0040 - val_loss: 0.0507
Epoch 480/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0042 - val_loss: 0.0574
Epoch 481/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0036 - val_loss: 0.0314
Epoch 482/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0047 - val_loss: 0.0819
Epoch 483/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0052 - val_loss: 0.

Epoch 634/1000
4/4 [==============================] - 0s 6ms/sample - loss: 5.1001e-04 - val_loss: 0.0169
Epoch 635/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0018 - val_loss: 0.0081
Epoch 636/1000
4/4 [==============================] - 0s 6ms/sample - loss: 0.0016 - val_loss: 0.0120
Epoch 637/1000
4/4 [==============================] - 0s 6ms/sample - loss: 5.0877e-04 - val_loss: 0.0127
Epoch 638/1000
4/4 [==============================] - 0s 6ms/sample - loss: 5.5450e-04 - val_loss: 0.0070
Epoch 639/1000
4/4 [==============================] - 0s 6ms/sample - loss: 7.1253e-04 - val_loss: 0.0114
Epoch 640/1000
4/4 [==============================] - 0s 7ms/sample - loss: 0.0011 - val_loss: 0.0097
Epoch 641/1000
4/4 [==============================] - 0s 6ms/sample - loss: 6.4172e-04 - val_loss: 0.0096
Epoch 642/1000
4/4 [==============================] - 0s 7ms/sample - loss: 3.2931e-04 - val_loss: 0.0110
Epoch 643/1000
4/4 [==============================] - 0s 7

Epoch 712/1000
4/4 [==============================] - 0s 6ms/sample - loss: 1.3810e-04 - val_loss: 0.0029
Epoch 713/1000
4/4 [==============================] - 0s 6ms/sample - loss: 3.3048e-04 - val_loss: 0.0073
Epoch 714/1000
4/4 [==============================] - 0s 6ms/sample - loss: 2.4046e-04 - val_loss: 0.0029
Epoch 715/1000
4/4 [==============================] - 0s 7ms/sample - loss: 1.8152e-04 - val_loss: 0.0083
Epoch 716/1000
4/4 [==============================] - 0s 6ms/sample - loss: 4.7868e-04 - val_loss: 0.0026
Epoch 717/1000
4/4 [==============================] - 0s 6ms/sample - loss: 3.0557e-04 - val_loss: 0.0055
Epoch 718/1000
4/4 [==============================] - 0s 6ms/sample - loss: 6.3610e-05 - val_loss: 0.0034
Epoch 719/1000
4/4 [==============================] - 0s 6ms/sample - loss: 1.8823e-04 - val_loss: 0.0052
Epoch 720/1000
4/4 [==============================] - 0s 8ms/sample - loss: 1.8709e-04 - val_loss: 0.0019
Epoch 721/1000
4/4 [==========================

4/4 [==============================] - 0s 6ms/sample - loss: 1.5129e-04 - val_loss: 0.0039
Epoch 866/1000
4/4 [==============================] - 0s 6ms/sample - loss: 2.3884e-04 - val_loss: 3.7240e-04
Epoch 867/1000
4/4 [==============================] - 0s 6ms/sample - loss: 1.3244e-04 - val_loss: 0.0017
Epoch 868/1000
4/4 [==============================] - 0s 6ms/sample - loss: 2.1550e-04 - val_loss: 0.0013
Epoch 869/1000
4/4 [==============================] - 0s 6ms/sample - loss: 2.8108e-04 - val_loss: 4.7950e-05
Epoch 870/1000
4/4 [==============================] - 0s 6ms/sample - loss: 4.7495e-04 - val_loss: 0.0042
Epoch 871/1000
4/4 [==============================] - 0s 6ms/sample - loss: 5.1515e-04 - val_loss: 1.2177e-05
Epoch 872/1000
4/4 [==============================] - 0s 7ms/sample - loss: 2.1583e-04 - val_loss: 0.0021
Epoch 873/1000
4/4 [==============================] - 0s 6ms/sample - loss: 2.1376e-04 - val_loss: 4.6527e-04
Epoch 874/1000
4/4 [=========================

Epoch 941/1000
4/4 [==============================] - 0s 6ms/sample - loss: 1.1138e-04 - val_loss: 0.0020
Epoch 942/1000
4/4 [==============================] - 0s 7ms/sample - loss: 5.2196e-05 - val_loss: 2.3783e-04
Epoch 943/1000
4/4 [==============================] - 0s 7ms/sample - loss: 1.4852e-04 - val_loss: 9.6764e-04
Epoch 944/1000
4/4 [==============================] - 0s 7ms/sample - loss: 4.1062e-05 - val_loss: 0.0018
Epoch 945/1000
4/4 [==============================] - 0s 7ms/sample - loss: 2.7791e-05 - val_loss: 6.8107e-04
Epoch 946/1000
4/4 [==============================] - 0s 6ms/sample - loss: 2.4921e-05 - val_loss: 0.0020
Epoch 947/1000
4/4 [==============================] - 0s 6ms/sample - loss: 3.4931e-05 - val_loss: 0.0012
Epoch 948/1000
4/4 [==============================] - 0s 6ms/sample - loss: 6.2371e-05 - val_loss: 7.5757e-04
Epoch 949/1000
4/4 [==============================] - 0s 6ms/sample - loss: 3.5341e-05 - val_loss: 0.0025
Epoch 950/1000
4/4 [==========

In [4]:
# result
prediction = model.predict(x_test)
print(prediction)

print("실제값: {:.3f}, 예측값: {:.3f}".format(y_test[0], prediction[0][0]))

[[9.8500395]]
실제값: 10.000, 예측값: 9.850
