In [4]:
import numpy as np

# Data
a = np.array(range(1, 11))                     # a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]    (10, )
                                               #      0  1  2  3  4  5  6  7  8   9 
size = 5                                       # 자르는 크기

# data_split
def split_x(seq, size):
    lst = []
    for i in range(len(seq) - size + 1):       # len = length  : 길이  i in range(6)  : [0, 1, 2, 3, 4, 5]
        subset = seq[i : (i + size)]           # i =0,  subset = a[ 0 : 5 ] = [ 1, 2, 3, 4, 5]
        lst.append([item for item in subset])  # aaa = [[1, 2, 3, 4, 5]]
    return np.array(lst)

dataset = split_x(a, size)                      # dataset.shape = ((len(a) - size +1) , size)
print(dataset)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
