In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [2]:
data = pd.DataFrame(iris.data, columns=iris.feature_names)
s = pd.Series(iris.target, dtype='category')
s = s.cat.rename_categories(iris.target_names)
data['species'] = s
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scale_cols = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
data_scaled = scaler.fit_transform(data[scale_cols])
X = data_scaled
print(X.shape)

(150, 4)


In [20]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
la = LabelEncoder()

Y = la.fit_transform(data['species'])
Y_encoded = tf.keras.utils.to_categorical(Y)
print(Y_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_re, y_train, y_re = train_test_split(X, Y_encoded, shuffle=True, test_size=0.2)
x_val, x_test, y_val, y_test = train_test_split(x_re, y_re, shuffle=True, test_size=0.5)
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(120, 4)
(15, 4)
(15, 4)
(120, 3)
(15, 3)
(15, 3)


In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(20, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 20)                100       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 343
Trainable params: 343
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=100, batch_size=1, verbose=1)

Train on 120 samples, validate on 15 samples
Epoch 1/100
120/120 [==============================] - 1s 11ms/sample - loss: 1.0680 - accuracy: 0.3833 - val_loss: 1.0586 - val_accuracy: 0.2000
Epoch 2/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.9432 - accuracy: 0.3917 - val_loss: 0.9373 - val_accuracy: 0.5333
Epoch 3/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.8016 - accuracy: 0.6917 - val_loss: 0.7420 - val_accuracy: 0.8667
Epoch 4/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.6802 - accuracy: 0.8083 - val_loss: 0.5714 - val_accuracy: 0.9333
Epoch 5/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.5666 - accuracy: 0.8250 - val_loss: 0.4321 - val_accuracy: 1.0000
Epoch 6/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.4886 - accuracy: 0.9000 - val_loss: 0.3309 - val_accuracy: 1.0000
Epoch 7/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.4185 

Epoch 57/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.1129 - accuracy: 0.9417 - val_loss: 0.0063 - val_accuracy: 1.0000
Epoch 58/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.0855 - accuracy: 0.9583 - val_loss: 0.0068 - val_accuracy: 1.0000
Epoch 59/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.0859 - accuracy: 0.9583 - val_loss: 0.0169 - val_accuracy: 1.0000
Epoch 60/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.0673 - accuracy: 0.9583 - val_loss: 0.0210 - val_accuracy: 1.0000
Epoch 61/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.0824 - accuracy: 0.9583 - val_loss: 0.0119 - val_accuracy: 1.0000
Epoch 62/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.0748 - accuracy: 0.9583 - val_loss: 0.0283 - val_accuracy: 1.0000
Epoch 63/100
120/120 [==============================] - 0s 2ms/sample - loss: 0.0844 - accuracy: 0.9583 - val_loss: 0.0105 -

In [24]:
evaluate = model.evaluate(x_test, y_test, batch_size=1, verbose=2)
evaluate

15/1 - 0s - loss: 0.0173 - accuracy: 1.0000


[0.03452163798137917, 1.0]

In [30]:
import numpy as np

predict = model.predict(x_test)
for i in range(len(y_test)):
    label = la.classes_[np.argmax(y_test[i])]
    predict = la.classes_[np.argmax(prediction[i])]
    print("실제값: {}, 예측값: {}".format(label, predict))

실제값: virginica, 예측값: virginica
실제값: virginica, 예측값: virginica
실제값: virginica, 예측값: virginica
실제값: setosa, 예측값: setosa
실제값: versicolor, 예측값: versicolor
실제값: versicolor, 예측값: versicolor
실제값: versicolor, 예측값: versicolor
실제값: setosa, 예측값: setosa
실제값: setosa, 예측값: setosa
실제값: setosa, 예측값: setosa
실제값: setosa, 예측값: setosa
실제값: versicolor, 예측값: versicolor
실제값: setosa, 예측값: setosa
실제값: virginica, 예측값: virginica
실제값: setosa, 예측값: setosa
