In [1]:
# import library
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# seed
import os
seed = 123
os.environ['PYTHONHASHSEED'] = str(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

In [2]:
# dataset
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([1,0,1,0,1,0,1,0,1,0])
print(x)
print(y)

# label encoder
e = LabelEncoder()
e.fit(y)
Y = e.transform(y)
y_encoded = tf.keras.utils.to_categorical(Y)
print(y_encoded)

[ 1  2  3  4  5  6  7  8  9 10]
[1 0 1 0 1 0 1 0 1 0]
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [3]:
# split dataset
x_train_val, x_test, y_train_val, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=seed)
x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val, test_size=0.2, random_state=seed)

x_train = x_train[:,np.newaxis]
x_val = x_val[:,np.newaxis]
x_test = x_test[:,np.newaxis]

print(x_train.shape, y_train.shape, x_val.shape, y_val.shape, x_test.shape, y_test.shape)

(6, 1) (6, 2) (2, 1) (2, 2) (2, 1) (2, 2)


In [4]:
# model structure
model = Sequential()
model.add(Dense(10, input_dim = x_train.shape[1], activation='relu'))
#model.add(Dense(5, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                20        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 22        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [5]:
# model training
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=500, batch_size=2, verbose=1)

Train on 6 samples, validate on 2 samples
Epoch 1/500
6/6 [==============================] - 1s 194ms/sample - loss: 0.7060 - accuracy: 0.5000 - val_loss: 0.6351 - val_accuracy: 1.0000
Epoch 2/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.7003 - accuracy: 0.5000 - val_loss: 0.6461 - val_accuracy: 1.0000
Epoch 3/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6981 - accuracy: 0.5000 - val_loss: 0.6521 - val_accuracy: 1.0000
Epoch 4/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6984 - accuracy: 0.5000 - val_loss: 0.6624 - val_accuracy: 1.0000
Epoch 5/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6965 - accuracy: 0.5000 - val_loss: 0.6682 - val_accuracy: 1.0000
Epoch 6/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6966 - accuracy: 0.5000 - val_loss: 0.6765 - val_accuracy: 1.0000
Epoch 7/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6945 - accuracy: 0.5000 - val_loss:

6/6 [==============================] - 0s 4ms/sample - loss: 0.6900 - accuracy: 0.5000 - val_loss: 0.7693 - val_accuracy: 0.0000e+00
Epoch 58/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6900 - accuracy: 0.5000 - val_loss: 0.7684 - val_accuracy: 0.0000e+00
Epoch 59/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6903 - accuracy: 0.5000 - val_loss: 0.7707 - val_accuracy: 0.0000e+00
Epoch 60/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6894 - accuracy: 0.5000 - val_loss: 0.7697 - val_accuracy: 0.0000e+00
Epoch 61/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6894 - accuracy: 0.5000 - val_loss: 0.7705 - val_accuracy: 0.0000e+00
Epoch 62/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6894 - accuracy: 0.5000 - val_loss: 0.7700 - val_accuracy: 0.0000e+00
Epoch 63/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6904 - accuracy: 0.5000 - val_loss: 0.7660 - val_accuracy: 0.

6/6 [==============================] - 0s 4ms/sample - loss: 0.6883 - accuracy: 0.6667 - val_loss: 0.7709 - val_accuracy: 0.0000e+00
Epoch 114/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6887 - accuracy: 0.6667 - val_loss: 0.7677 - val_accuracy: 0.0000e+00
Epoch 115/500
6/6 [==============================] - 0s 3ms/sample - loss: 0.6887 - accuracy: 0.6667 - val_loss: 0.7644 - val_accuracy: 0.0000e+00
Epoch 116/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6885 - accuracy: 0.6667 - val_loss: 0.7685 - val_accuracy: 0.0000e+00
Epoch 117/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6884 - accuracy: 0.6667 - val_loss: 0.7663 - val_accuracy: 0.0000e+00
Epoch 118/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6890 - accuracy: 0.6667 - val_loss: 0.7712 - val_accuracy: 0.0000e+00
Epoch 119/500
6/6 [==============================] - 0s 3ms/sample - loss: 0.6887 - accuracy: 0.6667 - val_loss: 0.7681 - val_accura

6/6 [==============================] - 0s 4ms/sample - loss: 0.6870 - accuracy: 0.5000 - val_loss: 0.7613 - val_accuracy: 0.0000e+00
Epoch 169/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6874 - accuracy: 0.5000 - val_loss: 0.7655 - val_accuracy: 0.0000e+00
Epoch 170/500
6/6 [==============================] - 0s 3ms/sample - loss: 0.6870 - accuracy: 0.5000 - val_loss: 0.7654 - val_accuracy: 0.0000e+00
Epoch 171/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6869 - accuracy: 0.5000 - val_loss: 0.7684 - val_accuracy: 0.0000e+00
Epoch 172/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6878 - accuracy: 0.5000 - val_loss: 0.7641 - val_accuracy: 0.0000e+00
Epoch 173/500
6/6 [==============================] - 0s 6ms/sample - loss: 0.6863 - accuracy: 0.5000 - val_loss: 0.7655 - val_accuracy: 0.0000e+00
Epoch 174/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6864 - accuracy: 0.5000 - val_loss: 0.7673 - val_accura

Epoch 224/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6858 - accuracy: 0.5000 - val_loss: 0.7672 - val_accuracy: 0.0000e+00
Epoch 225/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6860 - accuracy: 0.5000 - val_loss: 0.7699 - val_accuracy: 0.0000e+00
Epoch 226/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6855 - accuracy: 0.5000 - val_loss: 0.7672 - val_accuracy: 0.0000e+00
Epoch 227/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6859 - accuracy: 0.5000 - val_loss: 0.7699 - val_accuracy: 0.0000e+00
Epoch 228/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6853 - accuracy: 0.5000 - val_loss: 0.7682 - val_accuracy: 0.0000e+00
Epoch 229/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6861 - accuracy: 0.5000 - val_loss: 0.7648 - val_accuracy: 0.0000e+00
Epoch 230/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6860 - accuracy: 0.5000 - val_loss: 0.762

Epoch 280/500
6/6 [==============================] - 0s 6ms/sample - loss: 0.6861 - accuracy: 0.6667 - val_loss: 0.7712 - val_accuracy: 0.0000e+00
Epoch 281/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6848 - accuracy: 0.6667 - val_loss: 0.7695 - val_accuracy: 0.0000e+00
Epoch 282/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6847 - accuracy: 0.6667 - val_loss: 0.7716 - val_accuracy: 0.0000e+00
Epoch 283/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6844 - accuracy: 0.6667 - val_loss: 0.7713 - val_accuracy: 0.0000e+00
Epoch 284/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6853 - accuracy: 0.6667 - val_loss: 0.7746 - val_accuracy: 0.0000e+00
Epoch 285/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6853 - accuracy: 0.6667 - val_loss: 0.7704 - val_accuracy: 0.0000e+00
Epoch 286/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6845 - accuracy: 0.6667 - val_loss: 0.771

Epoch 336/500
6/6 [==============================] - 0s 3ms/sample - loss: 0.6843 - accuracy: 0.6667 - val_loss: 0.7603 - val_accuracy: 0.0000e+00
Epoch 337/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6839 - accuracy: 0.6667 - val_loss: 0.7589 - val_accuracy: 0.0000e+00
Epoch 338/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6836 - accuracy: 0.6667 - val_loss: 0.7588 - val_accuracy: 0.0000e+00
Epoch 339/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6844 - accuracy: 0.6667 - val_loss: 0.7631 - val_accuracy: 0.0000e+00
Epoch 340/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6835 - accuracy: 0.6667 - val_loss: 0.7647 - val_accuracy: 0.0000e+00
Epoch 341/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6843 - accuracy: 0.6667 - val_loss: 0.7675 - val_accuracy: 0.0000e+00
Epoch 342/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6835 - accuracy: 0.6667 - val_loss: 0.766

Epoch 392/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6834 - accuracy: 0.6667 - val_loss: 0.7610 - val_accuracy: 0.0000e+00
Epoch 393/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6828 - accuracy: 0.6667 - val_loss: 0.7610 - val_accuracy: 0.0000e+00
Epoch 394/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6836 - accuracy: 0.6667 - val_loss: 0.7593 - val_accuracy: 0.0000e+00
Epoch 395/500
6/6 [==============================] - 0s 3ms/sample - loss: 0.6834 - accuracy: 0.6667 - val_loss: 0.7594 - val_accuracy: 0.0000e+00
Epoch 396/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6840 - accuracy: 0.6667 - val_loss: 0.7564 - val_accuracy: 0.0000e+00
Epoch 397/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6834 - accuracy: 0.6667 - val_loss: 0.7611 - val_accuracy: 0.0000e+00
Epoch 398/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6830 - accuracy: 0.6667 - val_loss: 0.762

Epoch 448/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6829 - accuracy: 0.6667 - val_loss: 0.7661 - val_accuracy: 0.0000e+00
Epoch 449/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6826 - accuracy: 0.6667 - val_loss: 0.7632 - val_accuracy: 0.0000e+00
Epoch 450/500
6/6 [==============================] - ETA: 0s - loss: 0.6158 - accuracy: 1.00 - 0s 3ms/sample - loss: 0.6823 - accuracy: 0.6667 - val_loss: 0.7639 - val_accuracy: 0.0000e+00
Epoch 451/500
6/6 [==============================] - 0s 5ms/sample - loss: 0.6837 - accuracy: 0.6667 - val_loss: 0.7593 - val_accuracy: 0.0000e+00
Epoch 452/500
6/6 [==============================] - 0s 3ms/sample - loss: 0.6832 - accuracy: 0.6667 - val_loss: 0.7564 - val_accuracy: 0.0000e+00
Epoch 453/500
6/6 [==============================] - 0s 4ms/sample - loss: 0.6823 - accuracy: 0.6667 - val_loss: 0.7566 - val_accuracy: 0.0000e+00
Epoch 454/500
6/6 [==============================] - 0s 5ms/sample - loss: 0

In [6]:
# result
prediction = model.predict(x_test)
for i in range(len(y_test)):
    label = np.argmax(y_test[i])
    predict = np.argmax(prediction[i])
    print("실제값: {:.3f}, 예측값: {:.3f}".format(label, predict))

실제값: 1.000, 예측값: 1.000
실제값: 1.000, 예측값: 0.000
