In [1]:
# import library
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# seed
import os
seed = 123
os.environ['PYTHONHASHSEED'] = str(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

In [2]:
# dataset
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([1,2,3,4,5,1,2,3,4,5])
print(x)
print(y)

# label encoder
e = LabelEncoder()
e.fit(y)
Y = e.transform(y)
y_encoded = tf.keras.utils.to_categorical(Y)
print(y_encoded)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 1 2 3 4 5]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
# split dataset
x_train_val, x_test, y_train_val, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=seed)
x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val, test_size=0.2, random_state=seed)

x_train = x_train[:,np.newaxis]
x_val = x_val[:,np.newaxis]
x_test = x_test[:,np.newaxis]

print(x_train.shape, y_train.shape, x_val.shape, y_val.shape, x_test.shape, y_test.shape)

(6, 1) (6, 5) (2, 1) (2, 5) (2, 1) (2, 5)


In [4]:
# model structure
model = Sequential()
model.add(Dense(20, input_dim = x_train.shape[1], activation='relu'))
model.add(Dense(17, activation='relu'))
model.add(Dense(14, activation='relu'))
model.add(Dense(11, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(5, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 20)                40        
_________________________________________________________________
dense_1 (Dense)              (None, 17)                357       
_________________________________________________________________
dense_2 (Dense)              (None, 14)                252       
_________________________________________________________________
dense_3 (Dense)              (None, 11)                165       
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 96        
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 45        
Total params: 955
Trainable params: 955
Non-trainable params: 0
__________________________________________________________

In [5]:
# model training
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=1000, batch_size=4, verbose=1)

Train on 6 samples, validate on 2 samples
Epoch 1/1000
6/6 [==============================] - 1s 101ms/sample - loss: 1.5985 - accuracy: 0.3333 - val_loss: 1.6623 - val_accuracy: 0.0000e+00
Epoch 2/1000
6/6 [==============================] - 0s 4ms/sample - loss: 1.5942 - accuracy: 0.3333 - val_loss: 1.6723 - val_accuracy: 0.0000e+00
Epoch 3/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.5921 - accuracy: 0.3333 - val_loss: 1.6845 - val_accuracy: 0.0000e+00
Epoch 4/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.5882 - accuracy: 0.3333 - val_loss: 1.6965 - val_accuracy: 0.0000e+00
Epoch 5/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5881 - accuracy: 0.3333 - val_loss: 1.7079 - val_accuracy: 0.0000e+00
Epoch 6/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5834 - accuracy: 0.3333 - val_loss: 1.7154 - val_accuracy: 0.0000e+00
Epoch 7/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.5812

6/6 [==============================] - 0s 2ms/sample - loss: 1.5105 - accuracy: 0.3333 - val_loss: 2.1416 - val_accuracy: 0.0000e+00
Epoch 57/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5093 - accuracy: 0.3333 - val_loss: 2.1473 - val_accuracy: 0.0000e+00
Epoch 58/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5086 - accuracy: 0.3333 - val_loss: 2.1560 - val_accuracy: 0.0000e+00
Epoch 59/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5076 - accuracy: 0.3333 - val_loss: 2.1636 - val_accuracy: 0.0000e+00
Epoch 60/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5063 - accuracy: 0.3333 - val_loss: 2.1683 - val_accuracy: 0.0000e+00
Epoch 61/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5056 - accuracy: 0.3333 - val_loss: 2.1757 - val_accuracy: 0.0000e+00
Epoch 62/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.5043 - accuracy: 0.3333 - val_loss: 2.1799 - val_accura

Epoch 112/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4627 - accuracy: 0.3333 - val_loss: 2.3437 - val_accuracy: 0.0000e+00
Epoch 113/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4623 - accuracy: 0.3333 - val_loss: 2.3431 - val_accuracy: 0.0000e+00
Epoch 114/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4616 - accuracy: 0.3333 - val_loss: 2.3476 - val_accuracy: 0.0000e+00
Epoch 115/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4604 - accuracy: 0.3333 - val_loss: 2.3580 - val_accuracy: 0.0000e+00
Epoch 116/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4594 - accuracy: 0.3333 - val_loss: 2.3731 - val_accuracy: 0.0000e+00
Epoch 117/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4585 - accuracy: 0.3333 - val_loss: 2.3896 - val_accuracy: 0.0000e+00
Epoch 118/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4591 - accuracy: 0.3333 - val_loss

6/6 [==============================] - 0s 2ms/sample - loss: 1.4272 - accuracy: 0.1667 - val_loss: 2.5331 - val_accuracy: 0.0000e+00
Epoch 168/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.4263 - accuracy: 0.1667 - val_loss: 2.5414 - val_accuracy: 0.0000e+00
Epoch 169/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4258 - accuracy: 0.1667 - val_loss: 2.5463 - val_accuracy: 0.0000e+00
Epoch 170/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.4251 - accuracy: 0.1667 - val_loss: 2.5480 - val_accuracy: 0.0000e+00
Epoch 171/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.4244 - accuracy: 0.3333 - val_loss: 2.5480 - val_accuracy: 0.0000e+00
Epoch 172/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4239 - accuracy: 0.3333 - val_loss: 2.5469 - val_accuracy: 0.0000e+00
Epoch 173/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.4234 - accuracy: 0.3333 - val_loss: 2.5444 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.3988 - accuracy: 0.3333 - val_loss: 2.6463 - val_accuracy: 0.0000e+00
Epoch 223/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3987 - accuracy: 0.3333 - val_loss: 2.6489 - val_accuracy: 0.0000e+00
Epoch 224/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3984 - accuracy: 0.3333 - val_loss: 2.6492 - val_accuracy: 0.0000e+00
Epoch 225/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3978 - accuracy: 0.3333 - val_loss: 2.6562 - val_accuracy: 0.0000e+00
Epoch 226/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3973 - accuracy: 0.3333 - val_loss: 2.6614 - val_accuracy: 0.0000e+00
Epoch 227/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3965 - accuracy: 0.3333 - val_loss: 2.6725 - val_accuracy: 0.0000e+00
Epoch 228/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3964 - accuracy: 0.3333 - val_loss: 2.6873 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.3752 - accuracy: 0.3333 - val_loss: 2.8985 - val_accuracy: 0.0000e+00
Epoch 278/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3744 - accuracy: 0.3333 - val_loss: 2.9021 - val_accuracy: 0.0000e+00
Epoch 279/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3739 - accuracy: 0.3333 - val_loss: 2.9017 - val_accuracy: 0.0000e+00
Epoch 280/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3735 - accuracy: 0.3333 - val_loss: 2.9007 - val_accuracy: 0.0000e+00
Epoch 281/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3734 - accuracy: 0.3333 - val_loss: 2.8981 - val_accuracy: 0.0000e+00
Epoch 282/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3725 - accuracy: 0.3333 - val_loss: 2.8919 - val_accuracy: 0.0000e+00
Epoch 283/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3728 - accuracy: 0.3333 - val_loss: 2.8869 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.3532 - accuracy: 0.3333 - val_loss: 2.9520 - val_accuracy: 0.0000e+00
Epoch 333/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3533 - accuracy: 0.3333 - val_loss: 2.9729 - val_accuracy: 0.0000e+00
Epoch 334/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3525 - accuracy: 0.3333 - val_loss: 2.9879 - val_accuracy: 0.0000e+00
Epoch 335/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.3517 - accuracy: 0.3333 - val_loss: 2.9983 - val_accuracy: 0.0000e+00
Epoch 336/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.3513 - accuracy: 0.3333 - val_loss: 3.0145 - val_accuracy: 0.0000e+00
Epoch 337/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.3516 - accuracy: 0.3333 - val_loss: 3.0349 - val_accuracy: 0.0000e+00
Epoch 338/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3510 - accuracy: 0.3333 - val_loss: 3.0492 - val_

6/6 [==============================] - 0s 3ms/sample - loss: 1.3331 - accuracy: 0.3333 - val_loss: 3.2770 - val_accuracy: 0.0000e+00
Epoch 388/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3334 - accuracy: 0.3333 - val_loss: 3.2717 - val_accuracy: 0.0000e+00
Epoch 389/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3321 - accuracy: 0.3333 - val_loss: 3.2773 - val_accuracy: 0.0000e+00
Epoch 390/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3321 - accuracy: 0.3333 - val_loss: 3.2831 - val_accuracy: 0.0000e+00
Epoch 391/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3314 - accuracy: 0.3333 - val_loss: 3.2941 - val_accuracy: 0.0000e+00
Epoch 392/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3313 - accuracy: 0.3333 - val_loss: 3.3036 - val_accuracy: 0.0000e+00
Epoch 393/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3310 - accuracy: 0.3333 - val_loss: 3.3058 - val_

6/6 [==============================] - 0s 3ms/sample - loss: 1.3133 - accuracy: 0.3333 - val_loss: 3.4300 - val_accuracy: 0.0000e+00
Epoch 443/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.3134 - accuracy: 0.3333 - val_loss: 3.4403 - val_accuracy: 0.0000e+00
Epoch 444/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.3126 - accuracy: 0.3333 - val_loss: 3.4356 - val_accuracy: 0.0000e+00
Epoch 445/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3117 - accuracy: 0.3333 - val_loss: 3.4402 - val_accuracy: 0.0000e+00
Epoch 446/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3117 - accuracy: 0.3333 - val_loss: 3.4479 - val_accuracy: 0.0000e+00
Epoch 447/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3111 - accuracy: 0.3333 - val_loss: 3.4612 - val_accuracy: 0.0000e+00
Epoch 448/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.3114 - accuracy: 0.3333 - val_loss: 3.4701 - val_

6/6 [==============================] - 0s 3ms/sample - loss: 1.2933 - accuracy: 0.3333 - val_loss: 3.4748 - val_accuracy: 0.0000e+00
Epoch 498/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2931 - accuracy: 0.3333 - val_loss: 3.4978 - val_accuracy: 0.0000e+00
Epoch 499/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2930 - accuracy: 0.3333 - val_loss: 3.5235 - val_accuracy: 0.0000e+00
Epoch 500/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2922 - accuracy: 0.3333 - val_loss: 3.5411 - val_accuracy: 0.0000e+00
Epoch 501/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2920 - accuracy: 0.3333 - val_loss: 3.5556 - val_accuracy: 0.0000e+00
Epoch 502/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2917 - accuracy: 0.3333 - val_loss: 3.5764 - val_accuracy: 0.0000e+00
Epoch 503/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2918 - accuracy: 0.3333 - val_loss: 3.5920 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.2722 - accuracy: 0.5000 - val_loss: 3.7897 - val_accuracy: 0.0000e+00
Epoch 553/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2720 - accuracy: 0.5000 - val_loss: 3.7994 - val_accuracy: 0.0000e+00
Epoch 554/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2714 - accuracy: 0.5000 - val_loss: 3.7998 - val_accuracy: 0.0000e+00
Epoch 555/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2708 - accuracy: 0.5000 - val_loss: 3.7868 - val_accuracy: 0.0000e+00
Epoch 556/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2703 - accuracy: 0.5000 - val_loss: 3.7716 - val_accuracy: 0.0000e+00
Epoch 557/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2698 - accuracy: 0.5000 - val_loss: 3.7603 - val_accuracy: 0.0000e+00
Epoch 558/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2694 - accuracy: 0.5000 - val_loss: 3.7415 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.2494 - accuracy: 0.5000 - val_loss: 4.1650 - val_accuracy: 0.0000e+00
Epoch 608/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2498 - accuracy: 0.5000 - val_loss: 4.1948 - val_accuracy: 0.0000e+00
Epoch 609/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2488 - accuracy: 0.5000 - val_loss: 4.2058 - val_accuracy: 0.0000e+00
Epoch 610/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2496 - accuracy: 0.5000 - val_loss: 4.2213 - val_accuracy: 0.0000e+00
Epoch 611/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2482 - accuracy: 0.5000 - val_loss: 4.2128 - val_accuracy: 0.0000e+00
Epoch 612/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2478 - accuracy: 0.5000 - val_loss: 4.2064 - val_accuracy: 0.0000e+00
Epoch 613/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2477 - accuracy: 0.5000 - val_loss: 4.1999 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.2235 - accuracy: 0.5000 - val_loss: 4.3012 - val_accuracy: 0.0000e+00
Epoch 663/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2230 - accuracy: 0.5000 - val_loss: 4.3093 - val_accuracy: 0.0000e+00
Epoch 664/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2227 - accuracy: 0.5000 - val_loss: 4.3161 - val_accuracy: 0.0000e+00
Epoch 665/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2225 - accuracy: 0.5000 - val_loss: 4.3380 - val_accuracy: 0.0000e+00
Epoch 666/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2216 - accuracy: 0.5000 - val_loss: 4.3435 - val_accuracy: 0.0000e+00
Epoch 667/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.2212 - accuracy: 0.5000 - val_loss: 4.3624 - val_accuracy: 0.0000e+00
Epoch 668/1000
6/6 [==============================] - 0s 3ms/sample - loss: 1.2210 - accuracy: 0.5000 - val_loss: 4.3889 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 1.1432 - accuracy: 0.5000 - val_loss: 4.8906 - val_accuracy: 0.0000e+00
Epoch 718/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.1437 - accuracy: 0.3333 - val_loss: 4.9141 - val_accuracy: 0.0000e+00
Epoch 719/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.1384 - accuracy: 0.3333 - val_loss: 4.9401 - val_accuracy: 0.0000e+00
Epoch 720/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.1342 - accuracy: 0.3333 - val_loss: 4.9480 - val_accuracy: 0.0000e+00
Epoch 721/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.1296 - accuracy: 0.3333 - val_loss: 4.8957 - val_accuracy: 0.0000e+00
Epoch 722/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.1265 - accuracy: 0.3333 - val_loss: 4.8823 - val_accuracy: 0.0000e+00
Epoch 723/1000
6/6 [==============================] - 0s 2ms/sample - loss: 1.1214 - accuracy: 0.3333 - val_loss: 4.9114 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 0.8477 - accuracy: 0.6667 - val_loss: 6.3807 - val_accuracy: 0.0000e+00
Epoch 773/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.8428 - accuracy: 0.6667 - val_loss: 6.2957 - val_accuracy: 0.0000e+00
Epoch 774/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.8385 - accuracy: 0.6667 - val_loss: 6.3022 - val_accuracy: 0.0000e+00
Epoch 775/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.8323 - accuracy: 0.6667 - val_loss: 6.4231 - val_accuracy: 0.0000e+00
Epoch 776/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.8278 - accuracy: 0.6667 - val_loss: 6.4854 - val_accuracy: 0.0000e+00
Epoch 777/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.8217 - accuracy: 0.8333 - val_loss: 6.5203 - val_accuracy: 0.0000e+00
Epoch 778/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.8168 - accuracy: 0.6667 - val_loss: 6.5155 - val_

6/6 [==============================] - 0s 3ms/sample - loss: 0.6210 - accuracy: 0.6667 - val_loss: 9.3158 - val_accuracy: 0.0000e+00
Epoch 828/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.6204 - accuracy: 0.6667 - val_loss: 9.2133 - val_accuracy: 0.0000e+00
Epoch 829/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.6124 - accuracy: 0.6667 - val_loss: 9.2041 - val_accuracy: 0.0000e+00
Epoch 830/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.6087 - accuracy: 0.6667 - val_loss: 9.2169 - val_accuracy: 0.0000e+00
Epoch 831/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.6081 - accuracy: 0.6667 - val_loss: 9.2596 - val_accuracy: 0.0000e+00
Epoch 832/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.6049 - accuracy: 0.6667 - val_loss: 9.3758 - val_accuracy: 0.0000e+00
Epoch 833/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.6024 - accuracy: 0.6667 - val_loss: 9.5292 - val_

6/6 [==============================] - 0s 2ms/sample - loss: 0.5464 - accuracy: 0.6667 - val_loss: 12.5819 - val_accuracy: 0.0000e+00
Epoch 883/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5477 - accuracy: 0.6667 - val_loss: 12.6185 - val_accuracy: 0.0000e+00
Epoch 884/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5452 - accuracy: 0.6667 - val_loss: 12.7614 - val_accuracy: 0.0000e+00
Epoch 885/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5425 - accuracy: 0.6667 - val_loss: 12.8472 - val_accuracy: 0.0000e+00
Epoch 886/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5426 - accuracy: 0.6667 - val_loss: 12.9290 - val_accuracy: 0.0000e+00
Epoch 887/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5405 - accuracy: 0.6667 - val_loss: 12.9623 - val_accuracy: 0.0000e+00
Epoch 888/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5405 - accuracy: 0.6667 - val_loss: 13.0161

6/6 [==============================] - 0s 3ms/sample - loss: 0.5247 - accuracy: 0.6667 - val_loss: 15.0213 - val_accuracy: 0.0000e+00
Epoch 938/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5253 - accuracy: 0.6667 - val_loss: 15.0397 - val_accuracy: 0.0000e+00
Epoch 939/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5251 - accuracy: 0.6667 - val_loss: 15.0683 - val_accuracy: 0.0000e+00
Epoch 940/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5242 - accuracy: 0.6667 - val_loss: 15.0544 - val_accuracy: 0.0000e+00
Epoch 941/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5233 - accuracy: 0.6667 - val_loss: 15.0611 - val_accuracy: 0.0000e+00
Epoch 942/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5240 - accuracy: 0.6667 - val_loss: 15.0307 - val_accuracy: 0.0000e+00
Epoch 943/1000
6/6 [==============================] - 0s 2ms/sample - loss: 0.5236 - accuracy: 0.6667 - val_loss: 14.9869

6/6 [==============================] - 0s 3ms/sample - loss: 0.5162 - accuracy: 0.6667 - val_loss: 16.5939 - val_accuracy: 0.0000e+00
Epoch 993/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5178 - accuracy: 0.6667 - val_loss: 16.6033 - val_accuracy: 0.0000e+00
Epoch 994/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5160 - accuracy: 0.6667 - val_loss: 16.5804 - val_accuracy: 0.0000e+00
Epoch 995/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5151 - accuracy: 0.6667 - val_loss: 16.5447 - val_accuracy: 0.0000e+00
Epoch 996/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5160 - accuracy: 0.6667 - val_loss: 16.5135 - val_accuracy: 0.0000e+00
Epoch 997/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5146 - accuracy: 0.6667 - val_loss: 16.4470 - val_accuracy: 0.0000e+00
Epoch 998/1000
6/6 [==============================] - 0s 3ms/sample - loss: 0.5146 - accuracy: 0.6667 - val_loss: 16.3974

In [6]:
# result
prediction = model.predict(x_test)
for i in range(len(y_test)):
    label = np.argmax(y_test[i])
    predict = np.argmax(prediction[i])
    print("실제값: {:.3f}, 예측값: {:.3f}".format(label, predict))

실제값: 4.000, 예측값: 3.000
실제값: 0.000, 예측값: 1.000


In [7]:
prediction

array([[2.15564773e-06, 4.23949882e-02, 9.08846559e-04, 9.07969952e-01,
        4.87241074e-02],
       [7.28626219e-06, 9.99330163e-01, 3.30950483e-04, 1.19386255e-04,
        2.12305182e-04]], dtype=float32)